### ISSUE TITLE
Bug - Declaration of Yii2::doRequest(object $request) must be compatible with Client::doRequest($request)

### ISSUE THREAD

**Issue by ivanflashacademy** [Codeception/module-yii2#102]
Can someone remove type `object` for $request from this method Codeception\Lib\Connector\Yii2::doRequest(object $request) please?

**Comment by ivanflashacademy** [comment]
Any updates guys? It will take one minute to resolve this issue

**Comment by samdark** [comment]
Do you have time for a pull request?

**Comment by ivanflashacademy** [comment]
Hi Alexander
Yes, sure if I am authorised to do so because I have already tried to send a PR but encountered 403 error 
Thanks!

**Comment by samdark** [comment]
Fork repository first.

**Comment by W0rma** [comment]
@ivanflashacademy Which version of `symfony/browser-kit` is installed in your project? Version `5.0` or higher uses the `object` type. I assume you are currently using version `4.4` or lower?
