### ISSUE TITLE
Warning about "yiisoft/yii2-app-advanced" dependency after "composer install"

### ISSUE THREAD

**Issue by raimon-segura** [Codeception/module-yii2#103]
Hi!,

After doing "composer install" there is the following warning:
`Composer could not detect the root package (yiisoft/yii2-app-advanced) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version`

In my composer.lock I have this:
`
{
    "name": "codeception/module-yii2",
    "version": "1.1.5",
    "source": {
        "type": "git",
        "url": "https://github.com/Codeception/module-yii2.git",
        "reference": "14269d059b8eaedf3d414a673907bd874cd4ed04"
    },
    "dist": {
        "type": "zip",
        "url": "https://api.github.com/repos/Codeception/module-yii2/zipball/14269d059b8eaedf3d414a673907bd874cd4ed04",
        "reference": "14269d059b8eaedf3d414a673907bd874cd4ed04",
        "shasum": ""
    },
    "require": {
        "codeception/codeception": "^4.0",
        "codeception/lib-innerbrowser": "^1.0",
        "php": ">=5.6.0 <=8.1 | ~8.1.0"
    },
    "require-dev": {
        "codeception/module-asserts": "^1.3",
        "codeception/module-filesystem": "^1.0",
        "codeception/verify": "<2",
        "codemix/yii2-localeurls": "^1.7",
        "yiisoft/yii2": "dev-master",
        "yiisoft/yii2-app-advanced": "dev-master"
    },
    "type": "library",
    "autoload": {
        "classmap": [
            "src/"
        ]
    },
`

I gues that is because composer doesn't find the right package version ( "yiisoft/yii2-app-advanced": "dev-master" ) from: 'https://github.com/yiisoft/yii2-app-advanced/tags'

Maybe using someting like "yiisoft/yii2-app-advanced": "<2" " resolve the issue.

Many thanks!

**Comment by samdark** [comment]
Should be OK now with version from master.
