### ISSUE TITLE
Fixtures are not loaded when cleanup = false

### ISSUE THREAD

**Issue by wapmorgan** [Codeception/module-yii2#11]
If I set `cleanup` to false (to speed-up testing), this method does not load fixtures:
```php
private function loadFixtures($test)
    {
        $this->debugSection('Fixtures', 'Loading fixtures');
        if (empty($this->loadedFixtures)
            && method_exists($test, $this->_getConfig('fixturesMethod'))
        ) {
            $connectionWatcher = new Yii2Connector\ConnectionWatcher();
            $connectionWatcher->start();
            $this->haveFixtures(call_user_func([$test, $this->_getConfig('fixturesMethod')]));
            $connectionWatcher->stop();
            $connectionWatcher->closeAll();
        }
        $this->debugSection('Fixtures', 'Done');
    }
```

I think that `$this->loadedFixtures` is not empty after first fixtures loading in earlier test, and when codeception goes to another test, it does not load fixtures for it.

**Comment by wapmorgan** [comment]
I think, expected behavior for loading fixtures with `cleanap = false` is:
1. Load all fixtures from test case in the beggining of test case
2. Skip unloading fixtures in the end of test case
3. Reload fixtures (if previously tests loaded one fixture of declared in current test case)

**Comment by samdark** [comment]
@wapmorgan yes, your proposed behavior is better than current one, I think.

**Comment by samdark** [comment]
Want to implement the change

**Comment by SamMousa** [comment]
This seems to have been an attempt to make `loadFixtures` idempotent. Which isn't needed...
