### ISSUE TITLE
Acceptance test using amOnRoute leads to conflicts when using in combination WebDriver - improvement request

### ISSUE THREAD

**Issue by Proficoach** [Codeception/module-yii2#111]
When using WebDriver and Yii2 in acceptence.suite.yml without Yii2 part selection the AcceptanceTester ends in a conflict.
The amOnRoute is not assigned to a part and cannot be included when using this combination.

Suggestion: Add "@part route" with the amOnRoute method, and add to the part's list. 
This enables the method when using in combination with WebDriver.

### background
Codeception PHP Testing Framework v4.2.2 https://helpukrainewin.org/
Powered by PHPUnit 9.6.22 by Sebastian Bergmann and contributors.

In ModuleContainer.php line 543:
                                                                               
  [Codeception\Exception\ModuleConflictException]                              
  WebDriver module conflicts with Yii2                                         
                                                                               
  --                                                                           
  This usually happens when you enable two modules with the same actions but   
  with different backends.                                                     
  For instance, you can't run PhpBrowser, WebDriver, Laravel5 modules in one   
  suite,                                                                       
  as they implement similar methods but use different drivers to execute them  
  .                                                                            
  You can load a part of module (like: ORM) to avoid conflict.

**Comment by SamMousa** [comment]
Can you make a PR?

**Comment by Proficoach** [comment]
@SamMousa will be my first time making a PR.

**Comment by Proficoach** [comment]
@SamMousa  the PR is added. (Missing anything?)

**Comment by Proficoach** [comment]
[SOLVED]:  The AcceptanceTesterHelper contains the amOnRoute when using this Forked dev-yii2-part-route.

_HomeCest.php_ with:
......
$I->amOnRoute('site/index');
......
Passed the tests without "undefined method" errors

Background:

_acceptance.suite.yml_
actor: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: http://192.168.34.38:83/ # remote selenium server, port 83 Yii-basic / frontend
            browser: firefox
            host: 192.168.34.48
        - Yii2:
            part: [init,orm, route]
            entryScript: index-test.php
            cleanup: false
