### ISSUE TITLE
Yii2 - Unit-testing - Too many connections

### ISSUE THREAD

**Issue by goale** [Codeception/module-yii2#29]
#### What are you trying to achieve?

Running large suite of unit tests

#### What do you get instead?

```bash
[yii\db\Exception] SQLSTATE[HY000] [1040] Too many connections
```

After some investigation I found that ConnectionWatcher doesn't close connections initialized by the application.

```bash
- StudentWalletRepositoryTest: Persist existing wallet  Destroying application
  Starting application
  [ConnectionWatcher] watching new connections
  [Fixtures] Loading fixtures
  [Fixtures] Done
  [TransactionForcer] watching new connections
✔ StudentWalletRepositoryTest: Persist existing wallet (0.06s)
  [TransactionForcer] no longer watching new connections
  Destroying application
  [ConnectionWatcher] no longer watching new connections
  [ConnectionWatcher] closing all (0) connections

```

That happens because connection is being opened as soon as application starts (bootstraping some settings) and ConnectionWatcher doesn't catch it.

```php
// src/Codeception/Module/Yii2.php:299
$this->recreateClient();
$this->client->startApp(); // connection has been initialized here

$this->connectionWatcher = new Yii2Connector\ConnectionWatcher();
$this->connectionWatcher->start(); // watcher did not catch it
```

However, if I place ConnectionWatcher initialization before the app initialization, problem disappears.
```php
// src/Codeception/Module/Yii2.php:299
$this->connectionWatcher = new Yii2Connector\ConnectionWatcher();
$this->connectionWatcher->start();

$this->recreateClient();
$this->client->startApp(); // connection is caught by ConnectionWatcher
```

### Details

* Codeception version: 2.5.4
* PHP Version: 7.2.15

**Comment by DmLapin** [comment]
FYI. I have encountered with too many connections in functional tests.  New DB connection opens on every test request like `$tester->sendGet()` and stay opened untill all tests finish.

I see that \Codeception\Module\Yii2::_after use connectionWatcher to close all connections in case of simple unit tests. But in case of functional tests \Codeception\Lib\Connector\Yii2::doRequest doesn't use connectionWatcher. I dont know why but connections here are not closed even if recreateApplication = true.

**Comment by SamMousa** [comment]
It works for functional tests as well. Are you having the same issue as OP? If not create a separate issue.

**Comment by SamMousa** [comment]
Closing this since OP has not been responsive and clearly it's only an issue in a small subset of cases.
