### ISSUE TITLE
No longer possible to test with multiple mailers (Yii2)

### ISSUE THREAD

**Issue by VirtualRJ** [Codeception/module-yii2#31]
#### What are you trying to achieve?

For my application I have two mailer components defined. The default mailer component with the key 'mailer' is used for application specific mails and uses the company mailserver. The customer mailer (defined as a component 'customerMailer') is a specific configuration for the customer where they can use their own mailserver for sending out communication to their customers. Up until 2.3 I used the TestMailer class to mock this customerMailer as well since it is just a implementation of BaseMailer and exposes everything necessary to test the behavior.

My test.php in the common config directory looks like this and this would give me access to everything necessary for testing by accessing this component:

```php
    'components' => [
         ...
        'customerMailer' => [
            'class' => 'Codeception\Lib\Connector\Yii2\TestMailer',
        ],
    ],
```

#### What do you get instead?

Since Codeception/Codeception#5185 a lot of the features were moved from the TestMailer class to the Yii2 Connector class. The Connector class works perfectly fine for the default mailer component. But because it makes a lot of assumptions on using only the default mailer component it is no longer possible to mock different mailer instances with it. 

I see no way how to configure this new implementation of TestMailer class to store and handle mails without essentialy extending the TestMailer class and restoring functionality. 

### Details

* Codeception version: 2.5
* PHP Version: 7.0
* Operating System: Ubuntu
* Installation type: Composer
* Suite configuration:

```yml
class_name: UnitTester
bootstrap: false
modules:
    enabled:
        - Yii2:
            part: [orm, email, fixtures]
```

**Comment by SamMousa** [comment]
I'm closing this due to its age. If it is still relevant in current versions feel free to create a new issue.
