### ISSUE TITLE
REST module tests report 0% coverage

### ISSUE THREAD

**Issue by vitorhorta** [Codeception/module-yii2#46]
Hi,

I'm having the same problem that was reported on Codeception/Codeception#1622 but that solution didn't work for me.
I'm using Yii2 basic template and i'm trying to run Api tests that uses the REST module. The tests passes and the html files are created but I get 0 reports from coverage.

As mentioned on Codeception/Codeception#1622 I tried to downgrade the PHPUnit and Codeception version but it didn't work. Is there any other way to fix this issue? If not, what version should I use for both packages?

Thanks in advance

**Comment by SamMousa** [comment]
Closing this, it's old and about xdebug which you shouldn't use for code coverage.
