### ISSUE TITLE
php8.1

### ISSUE THREAD

**Issue by Krakozaber** [Codeception/module-yii2#57]
Problem 1
    - codeception/module-yii2[1.1.0, ..., 1.1.1] require php >=5.6.0 <8.0 -> your php version (8.1.0) does not satisfy that requirement.
    - codeception/module-yii2[1.1.2, ..., 1.1.3] require php >=5.6.0 <8.1 -> your php version (8.1.0) does not satisfy that requirement.
    - Root composer.json requires codeception/module-yii2 ~1.1.0 -> satisfiable by codeception/module-yii2[1.1.0, 1.1.1, 1.1.2, 1.1.3].

**Comment by Krakozaber** [comment]
https://github.com/Codeception/module-yii2/pull/55

Когда ожидать тег ?

**Comment by samdark** [comment]
Tagged.

**Comment by PonyPC** [comment]
8.1.1 please

**Comment by Krakozaber** [comment]
# 59

**Comment by PonyPC** [comment]
@Krakozaber Thanks
