### ISSUE TITLE
PhpBrowser::$client doesn't match it's parent InnerBrowser

### ISSUE THREAD

**Issue by rafaelmiti** [Codeception/module-yii2#58]
We just upgraded to PHP 8.0. We got an error when running the acceptance tests:

![failure](https://user-images.githubusercontent.com/6079888/147146956-372e1df2-e618-4c4d-ae70-15800ff6d685.png)

![wrong](https://user-images.githubusercontent.com/6079888/147146987-bb9b6ba2-a9d9-469c-9675-8fe3a101b457.png)

We could fix it by removing the type of the $client attribute of the PhpBrowser class (it was changed for the annotation really):

![success](https://user-images.githubusercontent.com/6079888/147147102-4405ce50-fe3e-4233-9e89-171b144f5b5c.png)

![right](https://user-images.githubusercontent.com/6079888/147147109-bea2c674-c14a-41bc-9332-bfeda8bf5468.png)

The PR if this is the right solution: https://github.com/Codeception/module-phpbrowser/pull/22

Obs: We tried to update to the version 2.1 of the module, because we couldn't find the 2.0 branch (against which the PR maybe should be opened), but it wasn't possible. Looks like composer can't update to it. So we hope this fix will be tagged by 2.0.x

**Comment by samdark** [comment]
@TavoNiievez would using `"codeception/lib-innerbrowser": "^1.0|^2.0" do the job? I don't see any obvious incompatibilities in 7.4 upgrade commit.

**Comment by TavoNiievez** [comment]
A priori the necessary changes occur as follows:

- [`src/Codeception/Lib/Connector/Yii2.php:L309`](https://github.com/Codeception/module-yii2/blob/f57b5587c2833f674aac68136823dec76a067382/src/Codeception/Lib/Connector/Yii2.php#L309)
```diff
- public function doRequest($request)
+ public function doRequest(object $request)
```

- [`src/Codeception/Module/Yii2.php:L701`](https://github.com/Codeception/module-yii2/blob/f57b5587c2833f674aac68136823dec76a067382/src/Codeception/Module/Yii2.php#L701)

```diff
- protected function clientRequest($method, $uri, array $parameters = [], array $files = [], array $server = [], $content = null, $changeHistory = true)
+ protected function clientRequest(string $method, string $uri,  array $parameters = [],  array $files = [], array $server = [], string $content = null, bool $changeHistory = true): \Symfony\Component\DomCrawler\Crawler
```

- [`src/Codeception/Module/Yii2.php:L814`](https://github.com/Codeception/module-yii2/blob/f57b5587c2833f674aac68136823dec76a067382/src/Codeception/Module/Yii2.php#L814)
```diff
- public function getInternalDomains()
+ public function getInternalDomains(): array
```

However, for this, support for any version of PHP lower than 7.2 should be removed, I commented via Slack that I wasn't sure if you would want to do this, or if you would reserve these changes for a hypothetical module-yii3.

Codeception 5 will require PHP 7.4 in addition, so you have to decide whether to keep backward compatibility with older versions of PHP or not.

**Comment by SamMousa** [comment]
We can just bump the module to major to 2? Since it is pretty stable and doesn't see a lot of bug reports version 2 could bump the required PHP version. If we do that, I'd personally prefer to just go to 8.1 though. Don't think it's worth it to bump the requirement to a version that's already / almost? EOL..

**Comment by TavoNiievez** [comment]
> would using `"codeception/lib-innerbrowser": "^1.0|^2.0" do the job?

you cannot support versions 1.x and 2.x at the same time because of these changes. So in the `composer.json`...
```diff
- "codeception/***": "^1.0",
+ "codeception/***": "^2.0",
```
Technically, support for PHP 7.2 or higher would be required at this time.
When Codeception 5 is launched it will require PHP 7.4 or higher.

Going straight for PHP 8.1 as @SamMousa suggests is an option too, but that's why I thought it would make more sense to do that by targeting yii3.

**Comment by samdark** [comment]
Bumping a version sounds alright but I think we should go 8.1 when Codeception will require it, not earlier.

Yii3 is a totally different framework so we can't reuse Yii2 module with it.

**Comment by Patrick-Remy** [comment]
I ran exactly in the same issue, if upgrading via `-W` to those versons
```
"codeception/module-phpbrowser": "^2.0",
"codeception/module-yii2": "^1.1",
```

the `codeception/lib-innerbrowser` gets bumped to v2 **without any error**. No idea why composer doesn't fail there. 

I would welcome if you release a v2 of this module like the other codeception modules that targets PHP 7.4, as it's currently not possible to upgrade to PHP8 for us, and many php libraries still support 7.4 + 8.0 as it's not a big deal for maintainers, but has a great benefit for all users.

Thanks for your work!

**Comment by TavoNiievez** [comment]
I believe this problem has been fixed and can be closed.

**Comment by TavoNiievez** [comment]
I think this issue has been fixed and can be closed.
