### ISSUE TITLE
Remove hidden dependency on SwiftMailer

### ISSUE THREAD

**Issue by SamMousa** [Codeception/module-yii2#64]
While moving away from SwiftMailer, since it is deprecated, I discovered that the mailer mocking functionality currently has a dependency on `yiisoft/yii2-swiftmailer`.

We should remove this and implement a simple message object implementation for testing purposes.

edit: In the mean time, a workaround is to configure your `messageClass` explicitly.

**Comment by developedsoftware** [comment]
I was going to make a pull request for this but come accross this issue? 

Have you made the required changes? 

Its causing my tests to fail for issue https://github.com/yiisoft/yii2-app-basic/issues/263#issuecomment-1149712062

**Comment by luke-** [comment]
@developedsoftware See here: https://github.com/yiisoft/yii2-app-basic/pull/264/

**Comment by developedsoftware** [comment]
Awesome thanks pal!

**Comment by developedsoftware** [comment]
@luke- do you plan on updating this repo? Specifically these two files here? Or have you made your fix inside the basic app directly? 

https://github.com/Codeception/module-yii2/search?q=swiftmailer

**Comment by luke-** [comment]
@developedsoftware No, I just recently had the same problem and therefore the quick PR for the Basic Template.

**Comment by SamMousa** [comment]
So this is still open for a PR if you want @developedsoftware. It needs to solve the dependency issue properly though, not by introducing a different dependency but by providing a minimal `MessageInterface` implementation that we can use.

**Comment by developedsoftware** [comment]
Understood.

**Comment by developedsoftware** [comment]
In the meantime the other PR should be accepted right ?

**Comment by SamMousa** [comment]
> In the meantime the other PR should be accepted right ?

That's not for me to decide, I don't use the templates and am not familiar with their config!
