### ISSUE TITLE
don not clear \Yii::$app->request->cookies every case 

### ISSUE THREAD

**Issue by zwb3707811** [Codeception/module-yii2#66]
#### What are you trying to achieve?
i want to use cookies value every case after i set cookies first
#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
every test use code ,but even i set cookies, next test cookies still null

  codecept_debug(\Yii::$app->request->cookies);

```
### Details

* Codeception version:
* PHP Version:
* Operating System:
* Installation type: Phar || Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
# paste suite config here
```

**Comment by SamMousa** [comment]
Tests are supposed to be clean slate. Cookies should be set in the browser module not the framework module. This is not a Yii issue, and probably not a bug in any case.

It is a bug if cookies set via the browser module get lost within a single test case, but not in this module.
