### ISSUE TITLE
Upgrading to PHP 8.0

### ISSUE THREAD

**Issue by remofernando** [Codeception/module-yii2#68]
Hi,
My name is Remo. I was trying to upgrade my application to PHP 8.0.
It seems like this module-yii2 module has no supporting version for codeception 4.1.3 (stable).
Most of its versions covers codeception ^4.0 but unfortunately that doesn't support PHP 8.0.
Is there any plan on creating newer version that supports codeception 4.1.3 and PHP 8.0?
If not, could you please tell me the work-around for this.

Remo

**Comment by SamMousa** [comment]
https://jubianchi.github.io/semver-check/#/^4.0/4.1.3
