### ISSUE TITLE
[Enhancement] Want's to see yii log in artifacts if test fails

### ISSUE THREAD

**Issue by aywan** [Codeception/module-yii2#7]
Hi.
I get a problems, when test run on another server with CI. It's hard to recreate same environment at local. In our code we are logging some exceptions and returning only error message without description. But at same moment everything writes to log.
But Codeception\Lib\Connector\Yii2\Logger send it only to Codeception debug, and it's not possible to see it without debug flag.

I propose sending this log to Codeception metadata artifacts. I quickly made "ugly" variant of solution https://github.com/Codeception/module-yii2/pull/8#issue-401418708

**Comment by SamMousa** [comment]
To me it makes more sense to have an option to send codeception debug logs to a file (ie not making this module specific).

**Comment by aywan** [comment]
Codeception is write logs to a file, into output directory. But application logs is missed there too.

**Comment by SamMousa** [comment]
I think the related PR was merged, so closing this!
