### ISSUE TITLE
Wrong documentation for `amOnPage()`

### ISSUE THREAD

**Issue by mytskine** [Codeception/module-yii2#81]
The `amOnPage()` method used to accept both a path (e.g. `/that/3`) and a route (e.g. `["/that/view", "id" => 3]`). This feature was removed, and the present method is not backward compatible. In fact, one can't use a full route anymore, except by splitting it into `amOnRoute()` (so upgrading an old test suite is painful). The problem is that the phpdoc was not updated:

```
     * @param string|array $page the URI or route in array format
     */
    public function amOnPage(string $page): void
```

**Comment by samdark** [comment]
Fixed by #86
